# Generated by Django 3.1.14 on 2022-07-22 17:18

import apps.schedule.models.specialreservation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20211022_1641'),
        ('schedule', '0009_term_ignore_conflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialreservation',
            name='classroom',
            field=models.ForeignKey(limit_choices_to={'can_reserve': True}, on_delete=django.db.models.deletion.CASCADE, to='courses.classroom', validators=[apps.schedule.models.specialreservation.validate_reserveable_classroom], verbose_name='sala'),
        ),
    ]
