# Generated by Django 3.1.14 on 2024-05-10 01:22

from django.db import migrations, models
import django.db.models.deletion

def update_entry_names(apps, schema_editor):
    Event = apps.get_model('schedule', 'Event')
    for event in Event.objects.all():
        if event.type == '5':
            event.title = (event.get_type_display() + ": " + event.thesis.title)[:255]
        elif event.type in ('0', '1') and event.course:
            event.title = (event.get_type_display() + ": " + event.course.name)[:255]
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_thesis_max_number_of_students'),
        ('schedule', '0010_auto_20220801_2026'),
        ('courses', '0036_auto_20211022_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theses.thesis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('0', 'Egzamin'), ('1', 'Kolokwium'), ('5', 'Obrona pracy dyplomowej'), ('2', 'Wydarzenie'), ('3', 'Zajęcia'), ('4', 'Inne')], max_length=1, verbose_name='Typ'),
        ),
        migrations.RunPython(update_entry_names),
    ]
