# Generated by Django 3.1.14 on 2024-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20220801_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Wydarzenie jest publiczne'),
        ),
    ]
