# Generated by Django 3.1.14 on 2025-01-05 14:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20211022_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinformation',
            name='effects',
        ),
        migrations.DeleteModel(
            name='Effects',
        ),
        migrations.CreateModel(
            name='ThematicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='nazwa skrócona')),
                ('full_name', models.CharField(max_length=250, verbose_name='nazwa pełna')),
                ('description', models.TextField(verbose_name='opis')),
            ],
            options={
                'verbose_name': 'Tag tematyczny (I st.)',
                'verbose_name_plural': 'Tagi tematyczne (I st.)',
            },
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='SpecialistTag',
        ),
        migrations.AlterModelOptions(
            name='specialisttag',
            options={'verbose_name': 'Tag specjalistyczny (II st.)', 'verbose_name_plural': 'Tagi specjalistyczne (II st.)'},
        ),
        migrations.RemoveField(
            model_name='courseinformation',
            name='tags',
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='specialist_tags',
            field=models.ManyToManyField(blank=True, to='courses.SpecialistTag', verbose_name='Tagi specjalistyczne (II st.)'),
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='thematic_tags',
            field=models.ManyToManyField(blank=True, to='courses.ThematicTag', verbose_name='Tagi tematyczne (I st.)'),
        ),
    ]
