# Generated by Django 3.1.14 on 2024-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20211022_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='records_pause',
            field=models.IntegerField(blank=True, default=2, help_text='Co ile minut powinny otwierać się zapisy dla kolejnej grupy studentów (według rankingu ECTS)', null=True, verbose_name='Przerwa między grupami studentów'),
        ),
    ]
