# Generated by Django 3.1.14 on 2025-01-05 14:57

from django.db import migrations, models

def add_specialist_tags(apps, schema_editor):
    SpecialistTag = apps.get_model('courses', 'SpecialistTag')

    tags = [
        ("AZ", "Algorytmika i złożoność obliczeniowa"),
        ("SY", "Systemy sieciowe i komputerowe"),
        ("PD", "Przetwarzanie danych"),
        ("NG", "Metody numeryczne i grafika komputerowa"),
        ("JP", "Języki programowania i logika"),
    ]

    for short_name, full_name in tags:
        SpecialistTag.objects.get_or_create(
            short_name=short_name,
            defaults={"full_name": full_name, "description": ""}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20211022_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinformation',
            name='effects',
        ),
        migrations.DeleteModel(
            name='Effects',
        ),
        migrations.CreateModel(
            name='SpecialistTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='nazwa skrócona')),
                ('full_name', models.CharField(max_length=250, verbose_name='nazwa pełna')),
                ('description', models.TextField(verbose_name='opis')),
            ],
            options={
                'verbose_name': 'Tag specjalistyczny (I st.)',
                'verbose_name_plural': 'Tagi specjalistyczne (I st.)',
            },
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='ThematicTag',
        ),
        migrations.AlterModelOptions(
            name='thematictag',
            options={'verbose_name': 'Tag specjalistyczny (II st.)', 'verbose_name_plural': 'Tagi specjalistyczne (II st.)'},
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='specialist_tags',
            field=models.ManyToManyField(blank=True, to='courses.SpecialistTag', verbose_name='Tagi specjalistyczne (II st.)'),
        ),
        migrations.RenameField(
            model_name='courseinformation',
            old_name='tags',
            new_name='thematic_tags',
        ),
        migrations.RunPython(add_specialist_tags),
    ]
