# Generated by Django 3.1.14 on 2024-04-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20211022_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_grade_beginning',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia oceny zajęć'),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_grade_ending',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia oceny zajęć'),
        ),
    ]
