# Generated by Django 3.1.14 on 2025-01-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20211022_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinformation',
            name='effects',
        ),
        migrations.DeleteModel(
            name='Effects',
        ),
    ]
