# Generated by Django 3.1.14 on 2024-05-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20240413_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='is_grade_active',
        ),
    ]
