# Generated by Django 3.1.3 on 2020-11-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_auto_20180525_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DontSendEntry',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
    ]
