# Generated by Django 3.1.14 on 2022-07-05 21:37

import apps.defects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nazwa')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=35, verbose_name='Miejsce')),
                ('description', models.TextField(blank=True, verbose_name='Opis usterki')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Zgłoszone'), (1, 'W oczekiwaniu na realizację'), (2, 'W realizacji'), (3, 'Zakończone')], default=0, verbose_name='Stan')),
                ('information_from_defect_manager', models.TextField(blank=True, verbose_name='Informacja od serwisanta')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=apps.defects.models.select_storage, upload_to='defect')),
                ('defect', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='defects.defect')),
            ],
        ),
        migrations.CreateModel(
            name='DefectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
