# Generated by Django 3.1.14 on 2023-05-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefectManager',
        ),
    ]
