---
- hosts: deploy

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:

    - name: Initialize the deploy root and gather facts
      become: yes
      become_user: "{{ deploy_user }}"
      deploy_helper:
        path: "/home/{{ deploy_user }}/deploy"
        state: present

    - name: Clone the project to the new release folder
      become: yes
      become_user: "{{ deploy_user }}"
      git:
        repo: 'https://github.com/iiuni/projektzapisy.git'
        dest: "{{ deploy_helper.new_release_path }}"
        version: ansible-deploy

    - name: Add an unfinished file, to allow cleanup on successful finalize
      become: yes
      file:
        path: "{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}"
        state: touch

    - name: Set up virtualenv and get requirements
      become: yes
      become_user: "{{ deploy_user }}"
      pip:
        virtualenv: "{{ deploy_helper.new_release_path }}/env3"
        virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
        requirements: "{{ deploy_helper.new_release_path }}/zapisy/requirements.development.txt"

    - name: Create logs directory
      become: yes
      file:
        path: "{{ deploy_helper.new_release_path }}/zapisy/logs"
        owner: "{{ deploy_user }}"
        state: directory
        group: "www-data"
        mode: '1775'

    - name: Create static directory
      become: yes
      become_user: "{{ deploy_user }}"
      file:
        path: "{{ deploy_helper.new_release_path }}/zapisy/static"
        state: directory

    - name: Create compiled_assets directory
      become: yes
      become_user: "{{ deploy_user }}"
      file:
        path: "{{ deploy_helper.new_release_path }}/zapisy/compiled_assets"
        state: directory

    - name: Apply migrates
      become: yes
      become_user: "{{ deploy_user }}"
      django_manage:
        command: migrate
        app_path: "{{ deploy_helper.new_release_path }}/zapisy"
        virtualenv: "{{ deploy_helper.new_release_path }}/env3"

    - name: Finalize the deploy, removing the unfinished file and switching the symlink
      become: yes
      become_user: "{{ deploy_user }}"
      deploy_helper:
        path: "/home/{{ deploy_user }}/deploy"
        release: "{{ deploy_helper.new_release }}"
        state: finalize
        clean: true
        keep_releases: 2

    - name: Create link to socket for Nginx
      become: yes
      become_user: "{{ deploy_user }}"
      file:
        src: "/home/{{ deploy_user }}/deploy/current/env3/run"
        dest: "/home/{{ deploy_user }}/deploy/current/zapisy/socket"
        force: yes
        state: link

    - name: Make sure that directory for gunicorn exists
      become: yes
      become_user: "{{ deploy_user }}"
      file:
        path: "/home/{{ deploy_user }}/deploy/current/env3/run/"
        state: directory

    - name: Start yarn
      systemd:
        name: yarn
        state: restarted
        enabled: no
      become: yes

    - name: Enable and run yarn_build service
      service:
        name: yarn_build
        enabled: no
        state: restarted
      become: yes

    - name: Django collect static files
      become: yes
      become_user: "{{ deploy_user }}"
      django_manage:
        command: collectstatic
        app_path: "/home/{{ deploy_user }}/deploy/current/zapisy"
        virtualenv: "/home/{{ deploy_user }}/deploy/current/env3"

    - name: Enable and run gunicorn socket
      become: yes
      service:
        name: gunicorn.socket
        enabled: yes
        state: restarted

    - name: Enable and run gunicorn service
      become: yes
      service:
        name: gunicorn
        enabled: yes
        state: restarted

    - name: Enable and run nginx service
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted

    - name: Enable and run rqworker1 service
      service:
        name: rqworker1
        enabled: yes
        state: restarted
      become: yes

    - name: Enable and run rqworker2 service
      service:
        name: rqworker2
        enabled: yes
        state: restarted
      become: yes
