---
- hosts: deploy

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Get revision
      shell: git rev-parse HEAD
      register: git_rev
      args:
        chdir: "/home/{{ deploy_user }}/deploy/current/"

    - name: Rollbar deployment notification
      rollbar_deployment:
        token: "{{ rollbar_token }}"
        environment: "{{ deploy_env }}"
        user: "{{ ansible_user }}"
        revision: "{{ git_rev.stdout }}"
        comment: "Deploy {{ ansible_host }}"
      when: rollbar_token != "none"