---

- hosts: server

  gather_facts: false

  tasks:
    - name: Replace a pattern with username in runserver service
      become: yes
      replace:
        path: /etc/systemd/system/yarn.service
        regexp: '\$user\$'
        replace: "{{ ansible_user }}"