# Generated by Django 3.1.14 on 2022-07-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201029_1347'),
        ('poll', '0009_auto_20201029_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pollview',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='unique_us_combination'),
        ),
    ]
