---
- hosts: all

  vars:
    PYTHON: "/usr/bin/python3"
    ansible_python_interpreter: "/usr/bin/python3"
    node_version: 18 # to be removed in the future (scroll down to "Install Node" tasks to learn why)

  tasks:

    # https://github.com/ansible/ansible/issues/25414#issuecomment-440549135
    - name: Wait for any possibly running unattended upgrade to finish
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
      become: yes

    # the following 3 tasks are to be removed once we migrate to a newer Ubuntu version
    # offering recent Node.js by default (not something like 10); this is a temporary workaround
    - name: Install Node - step 1
      get_url:
        url: "https://deb.nodesource.com/setup_{{ node_version }}.x"
        dest: /tmp/nodesource_setup.sh
        mode: "0755"
      become: yes

    - name: Install Node - step 2
      command: /tmp/nodesource_setup.sh
      become: yes

    - name: Install Node - step 3
      apt:
        name: nodejs
        state: latest
        update_cache: yes
      become: yes

    - name: Install yarn
      apt:
        pkg:
        - yarnpkg
        update_cache: yes
      become: yes

    - name: Install python3
      apt:
        pkg:
        - python3
        - python3-venv
        - python3-pip
      become: yes

    - name: Install redis
      apt:
        name: redis-server
      become: yes

    - name: Add source command to .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "source ~/env3/bin/activate"
        regex: "^source ~/env3/bin/activate$"
        state: present
        insertafter: EOF
        create: yes

    - name: Upgrade pip
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      pip:
        name: pip
        state: latest
        virtualenv: ~/env3
        virtualenv_command: "{{ PYTHON }} -m venv"

    - name: Set up virtualenv and get requirements
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      pip:
        virtualenv: ~/env3
        virtualenv_command: "{{ PYTHON }} -m venv"
        requirements: /vagrant/zapisy/requirements.development.txt

    - name: Create logs directory
      file:
        path: /vagrant/zapisy/logs
        state: directory
      become: yes

- name: Include playbook with postgres configuration
  import_playbook: postgres.yml

- name: Include playbook with services configuration
  import_playbook: services.yml
