---
- hosts: all

  tasks:
    - name: Deploy Django Runserver
      ansible.builtin.copy:
        src: runserver.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Deploy yarn install
      ansible.builtin.copy:
        src: yarn.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Deploy yarn dev:watch
      ansible.builtin.copy:
        src: yarn_dev_watch.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Deploy rqworker1
      ansible.builtin.copy:
        src: rqworker1.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Deploy rqworker2
      ansible.builtin.copy:
        src: rqworker2.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    # Enable and run
    - name: Systemd daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: yes
      become: yes

    - name: Enable and run Django Runserver service
      ansible.builtin.service:
        name: runserver
        enabled: yes
        state: started
      become: yes

    - name: Start yarn
      ansible.builtin.systemd_service:
        name: yarn
        enabled: yes
        state: started
      become: yes

    - name: Enable and run yarn_dev_watch service
      ansible.builtin.service:
        name: yarn_dev_watch
        enabled: yes
        state: started
      become: yes

    - name: Enable and run rqworker1 service
      ansible.builtin.service:
        name: rqworker1
        enabled: yes
        state: started
      become: yes

    - name: Enable and run rqworker2 service
      ansible.builtin.service:
        name: rqworker2
        enabled: yes
        state: started
      become: yes
