# Generated by Django 3.1.13 on 2021-12-12 16:00

import apps.theses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_auto_20201106_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='max_number_of_students',
            field=models.SmallIntegerField(blank=True, default=None, null=True, validators=[apps.theses.validators.validate_max_number_of_students]),
        ),
    ]
