# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-06 22:26
from __future__ import unicode_literals

from django.db import migrations


def remove_0_value_single_votes(apps, schema_editor):
    SingleVote = apps.get_model('vote', 'SingleVote')
    SingleVote.objects.filter(value=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180525_0559'),
    ]

    operations = [
        migrations.RunPython(remove_0_value_single_votes),
    ]
