# Generated by Django 2.0.8 on 2019-06-06 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferencesStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulled_from_queue', models.BooleanField(default=True, verbose_name='Zapisanie Cię do grupy')),
                ('not_pulled_from_queue', models.BooleanField(default=True, verbose_name='Niepowodzenie wciągnięcia Cię do grupy')),
                ('added_new_group', models.BooleanField(default=True, verbose_name='Dodanie nowej grupy przedmiotu, na który jesteś zapisany/a')),
                ('teacher_has_been_changed_enrolled', models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy, do której jesteś zapisany/a')),
                ('teacher_has_been_changed_queued', models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy, do której czekasz w kolejce')),
                ('terms_have_been_changed_enrolled', models.BooleanField(default=True, verbose_name='Zmiana terminu grupy, do której jesteś zapisany/a')),
                ('terms_have_been_changed_queued', models.BooleanField(default=True, verbose_name='Zmiana terminu grupy, do której czekasz w kolejce')),
                ('news_has_been_added', models.BooleanField(default=True, verbose_name='Powiadomienie o nowej wiadomości w Aktualnościach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreferencesTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_new_group_as_teacher', models.BooleanField(default=True, verbose_name='Przydzielenie do grupy')),
                ('news_has_been_added', models.BooleanField(default=True, verbose_name='Powiadomienie o nowej wiadomości w Aktualnościach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
    ]
