# Generated by Django 2.0.8 on 2019-05-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationpreferencesstudent_news_has_been_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreferencesstudent',
            name='not_pulled_from_queue',
        ),
        migrations.RemoveField(
            model_name='notificationpreferencesstudent',
            name='pulled_from_queue',
        ),
    ]
