# Generated by Django 3.0.10 on 2020-11-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationpreferencesteacher_thesis_voting_has_been_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferencesteacher',
            name='thesis_voting_has_been_activated',
            field=models.BooleanField(default=True, verbose_name='Powiadomienie o głosowaniu (dotyczy członka Komisji Prac Dyplomowych)'),
        ),
    ]
