# Generated by Django 3.1.14 on 2024-04-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20201010_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='event_has_been_accepted',
            field=models.BooleanField(default=True, verbose_name='Akceptacja Twojego wydarzenia'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='event_has_been_rejected',
            field=models.BooleanField(default=True, verbose_name='Odrzucenie Twojego wydarzenia'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesteacher',
            name='event_has_been_accepted',
            field=models.BooleanField(default=True, verbose_name='Akceptacja Twojego wydarzenia'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesteacher',
            name='event_has_been_rejected',
            field=models.BooleanField(default=True, verbose_name='Odrzucenie Twojego wydarzenia'),
        ),
    ]
