# Generated by Django 3.1.14 on 2024-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20201010_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesteacher',
            name='thesis_has_been_accepted',
            field=models.BooleanField(default=True, verbose_name='Powiadomienie o akceptacji pracy dyplomowej (dotyczy promotora i promotora wspierającego)'),
        ),
    ]
