# Generated by Django 2.0.8 on 2019-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20190510_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesteacher',
            name='news_has_been_added',
            field=models.BooleanField(default=True, verbose_name='Powiadomienie o nowej wiadomości w Aktualnościach'),
        ),
    ]
