# Generated by Django 3.1.14 on 2024-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationpreferencesteacher_thesis_has_been_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='event_decision',
            field=models.BooleanField(default=True, verbose_name='Decyzja w sprawie zgłoszonego przez Ciebie wydarzenia'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesteacher',
            name='event_decision',
            field=models.BooleanField(default=True, verbose_name='Decyzja w sprawie zgłoszonego przez Ciebie wydarzenia'),
        ),
    ]
