# Generated by Django 3.1.14 on 2024-02-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationpreferencesteacher_thesis_has_been_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferencesteacher',
            name='thesis_has_been_accepted',
            field=models.BooleanField(default=True, verbose_name='Powiadomienie o akceptacji tematu pracy dyplomowej'),
        ),
    ]
