# Generated by Django 2.0.8 on 2019-06-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notificationpreferencesteacher_news_has_been_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed',
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed_enrolled',
            field=models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy z przedmiotu, na który jesteś zapisany/a'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed_queued',
            field=models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy z przedmiotu, na który czekasz w kolejce'),
        ),
    ]
