# Generated by Django 2.0.8 on 2019-06-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20190602_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='student_has_been_enrolled',
            field=models.BooleanField(default=True, verbose_name='Zapisanie Cię do grupy'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='student_has_been_put_into_the_queue',
            field=models.BooleanField(default=True, verbose_name='Wciągniecie Cię do kolejki'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='terms_have_been_changed_enrolled',
            field=models.BooleanField(default=True, verbose_name='Zmiana terminu grupy, do której jesteś zapisany/a'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='terms_have_been_changed_queued',
            field=models.BooleanField(default=True, verbose_name='Zmiana terminu grupy, do której czekasz w kolejce'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed_enrolled',
            field=models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy, do której jesteś zapisany/a'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed_queued',
            field=models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy, do której czekasz w kolejce'),
        ),
    ]
