# Generated by Django 3.1.14 on 2024-07-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20240416_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='event_decision',
            field=models.BooleanField(default=True, verbose_name='Decyzja w sprawie zgłoszonego przez Ciebie wydarzenia'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesteacher',
            name='event_decision',
            field=models.BooleanField(default=True, verbose_name='Decyzja w sprawie zgłoszonego przez Ciebie wydarzenia'),
        ),
    ]
