# Generated by Django 2.0.8 on 2019-06-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20190604_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreferencesstudent',
            name='student_has_been_put_into_the_queue',
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='added_new_group',
            field=models.BooleanField(default=True, verbose_name='Dodanie nowej grupy przedmiotu, na który jesteś zapisany/a'),
        ),
    ]
