# Generated by Django 2.0.8 on 2019-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20190604_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreferencesstudent',
            old_name='student_has_been_enrolled',
            new_name='pulled_from_queue',
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='not_pulled_from_queue',
            field=models.BooleanField(default=True, verbose_name='Niepowodzenie wciągnięcia Cię do grupy'),
        ),
    ]
