# Generated by Django 3.1.5 on 2021-01-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0024_auto_20201029_1347'),
        ('courses', '0035_auto_20210126_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'program')},
            },
        ),
    ]
