# Generated by Django 3.1.4 on 2020-12-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201029_1347'),
        ('effects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedcourses',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.DeleteModel(
            name='CompletedEffects',
        ),
    ]
