# Generated by Django 3.1.14 on 2023-01-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201029_1347'),
        ('effects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa')),
                ('requirements', models.JSONField(verbose_name='Wymagania')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.program', verbose_name='Program studiów')),
            ],
            options={
                'verbose_name': 'Wymagania',
                'verbose_name_plural': 'Wymagania',
                'unique_together': {('name', 'program')},
            },
        ),
    ]
