# Generated by Django 3.1.4 on 2020-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20201106_2039'),
        ('effects', '0002_auto_20201220_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedcourses',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.CourseInstance'),
        ),
    ]
