# Generated by Django 2.1.15 on 2020-01-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0029_remove_term_classroom'),
        ('users', '0017_auto_20191020_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_course', models.CharField(max_length=100, unique=True, verbose_name='nazwa kursu schedulera')),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInstance', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'Mapa przedmiotów',
                'verbose_name_plural': 'Mapy przedmiotów',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_username', models.CharField(max_length=150, unique=True, verbose_name='username schedulera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='pracownik')),
            ],
            options={
                'verbose_name': 'Mapa pracowników',
                'verbose_name_plural': 'Mapy pracowników',
            },
        ),
        migrations.CreateModel(
            name='TermSyncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_id', models.PositiveIntegerField(null=True, verbose_name='id grupy w schedulerze')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Term', verbose_name='termin')),
            ],
            options={
                'verbose_name': 'Obiekt synchronizacji terminów grup',
                'verbose_name_plural': 'Obiekty synchronizacji terminów grup',
            },
        ),
    ]
