# Generated by Django 3.0.10 on 2020-10-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulersync', '0003_coursemap_employeemap'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS south_migrationhistory;'),
        migrations.RunSQL('DROP TABLE IF EXISTS auth_message;'),
    ]
