# Generated by Django 3.1.14 on 2023-01-07 21:58

from django.db import migrations, models
from django.db.models import Count, Min

def remove_duplicates(apps, schema_editor):
    Record = apps.get_model('records', 'Record')
    db_alias = schema_editor.connection.alias

    unique_fields = ['group_id', 'student_id']

    duplicates = (
        Record.objects.using(db_alias)
        .values(*unique_fields)
        .order_by()
        .annotate(oldest=Min('created'), count_id=Count('id'))
        .filter(count_id__gt=1)
    )

    for duplicate in duplicates:
        (
            Record.objects.using(db_alias)
            .filter(**{x: duplicate[x] for x in unique_fields})
            .exclude(created=duplicate['oldest'])
            .delete()
        )

class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20201106_2029'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 1), ('status', 0), _connector='OR'),
                fields=('group_id', 'student_id'),
                name='unique_enrolled_queued_record'),
        ),
    ]
