# Generated by Django 3.1.14 on 2023-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20201106_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='modified',
        ),
        migrations.AddField(
            model_name='record',
            name='modified_to_enrolled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='modified_to_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
