# Generated by Django 3.1.14 on 2023-05-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20201106_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Enrolled'), (2, 'Removed'), (3, 'Blocked')]),
        ),
    ]
