---
- hosts: localhost

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Create server folder
      file:
        path: /server
        state: directory

    - name: Install git
      apt:
        name: git
      become: yes

    - name: Initialize the deploy root and gather facts
      deploy_helper:
        path: /server/deploy
        state: present

    - name: Clone the project to the new release folder
      git:
        repo: 'https://github.com/iiuni/projektzapisy.git'
        dest: "{{ deploy_helper.new_release_path }}"
        version: ansible-deploy

    - name: Add an unfinished file, to allow cleanup on successful finalize
      become: true
      file:
        path: "{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}"
        state: touch

    - name: Finalize the deploy, removing the unfinished file and switching the symlink
      deploy_helper:
        path: /server/deploy
        release: "{{ deploy_helper.new_release }}"
        state: finalize
        clean: true
        keep_releases: 2