---
- hosts: all

  tasks:
    - name: Install apache2
      apt:
        name: apache2
      become: yes
      become_user: root
    - stat:
        path: /var/www
      register: sym_link
    - name: Delete /var/www in case it is not symbolic link
      file:
        path: sym_link.path
        state: absent
      when: sym_link.stat.exists and not sym_link.stat.islnk
    - name: Create /var/www if necessary
      file:
        src: /vagrant
        dest: /var/www
        state: link
      when: not sym_link.stat.exists or not sym_link.stat.islnk
    - name: Install apache2-dev
      apt:
        name: apache2-dev
    - name: Apt update and upgrade
      apt: 
        update_cache: yes
        upgrade: yes
      become: yes
      become_user: root
    - name: Add alias to .bash_alises
      lineinfile:
        path: ~/.bash_aliases
        line: "alias run='python /vagrant/zapisy/run.py'"
        regex: "^alias run='python /vagrant/zapisy/run.py'$"
        state: present
        insertafter: EOF
        create: yes
    - name: Add source command to .bashrc
      lineinfile:
        path: ~/.bashrc
        line: "source ~/env3/bin/activate"
        regex: "^source ~/env3/bin/activate$"
        state: present
        insertafter: EOF
        create: yes
    - name: Install pip
      apt:
        name: python-pip
        update_cache: yes
      become: yes
      become_user: root
    - name: Upgrade pip
      pip:
        name: pip
        state: latest
      args:
        chdir: ~/
    - name: Set up virtualenv and get requirements
      pip:
        virtualenv: env3
        virtualenv_python: python3.6
        requirements: /vagrant/zapisy/requirements.development.txt
      args:
        chdir: ~/
