---
- hosts: all

  tasks:
    - name: Install apache2
      apt:
        name: apache2
      become: yes
      become_user: root
    - stat:
        path: /var/www
      register: sym_link
    - name: Delete /var/www in case it is not symbolic link.
      file:
        path: sym_link.path
        state: absent
      when: sym_link.stat.exists and not sym_link.stat.islnk
    - name: Create /var/www if necessary
      file:
        src: /vagrant
        dest: /var/www
        state: link
      when: not sym_link.stat.exists or not sym_link.stat.islnk
    - name: Install apache2-dev
      apt:
        name: apache2-dev
    - name: Apt update and upgrade
      apt: 
        update_cache: yes
        upgrade: yes
      become: yes
      become_user: root
