---
- hosts: all

  vars:
    APP_DB_USER: fereol
    APP_DB_PASS: fereolpass
    APP_DB_NAME: fereol
    PG_VERSION: 10
    PYTHON: "/home/vagrant/env3/bin/python3"

  tasks:
    - name: Ensure a locale exists
      locale_gen:
        name: pl_PL.UTF-8
        state: present
      become: yes

    - name: Install postgresql-{{ PG_VERSION }}
      apt:
        name: postgresql-{{ PG_VERSION }}
        state: present
      become: yes

    - name: Install postgresql-contrib-{{ PG_VERSION }}
      apt:
        name: postgresql-contrib-{{ PG_VERSION }}
        state: present
      become: yes

    - name: Create the database user
      become: yes
      become_user: postgres
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      postgresql_user:
        name: "{{ APP_DB_USER }}"
        password: "{{ APP_DB_PASS }}"
        role_attr_flags: CREATEDB

    - name: Create the database
      become: yes
      become_user: postgres
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      postgresql_db:
        name: "{{ APP_DB_NAME }}"
        owner: "{{ APP_DB_USER }}"
        encoding: UTF-8
        lc_collate: pl_PL.UTF-8
        lc_ctype: pl_PL.UTF-8
        template: template0

    - stat:
        path: /vagrant/ii_zapisy_dump_dev.sql
      register: dumpsql

    - name: Update the database
      become: yes
      become_user: postgres
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      postgresql_db:
        name: "{{ APP_DB_NAME }}"
        state: restore
        target: "/vagrant/ii_zapisy_dump_dev.sql"
      when: dumpsql.stat.exists

    - name: Apply migrates to empty database
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      django_manage:
        command: migrate
        app_path: "/vagrant/zapisy"
        virtualenv: "/home/vagrant/env3"

    - debug:
        msg:
        - "Your PostgreSQL database has been setup and can be accessed on your local machine on the forwarded port (default: 15432)"
        - "Host: localhost"
        - "Port: 15432"
        - "Database: {{ APP_DB_NAME }}"
        - "Username: {{ APP_DB_USER }}"
        - "Password: {{ APP_DB_PASS }}"
        - ""
        - "Admin access to postgres user via VM:"
        - "vagrant ssh"
        - "sudo su - postgres"
        - ""
        - "psql access to app database user via VM:"
        - "vagrant ssh"
        - "sudo su - postgres"
        - "PGUSER={{ APP_DB_USER }} PGPASSWORD={{ APP_DB_PASS }} psql -h localhost {{ APP_DB_NAME }}"
        - ""
        - "Env variable for application development:"
        - "DATABASE_URL=postgresql://{{ APP_DB_USER }}:{{ APP_DB_PASS }}@localhost:15432/{{ APP_DB_NAME }}"
        - ""
        - "Local command to access the database via psql:"
        - "PGUSER={{ APP_DB_USER }} PGPASSWORD={{ APP_DB_PASS}} psql -h localhost -p 15432 {{ APP_DB_NAME }}"
      when: not logs_folder.stat.exists
