---
- hosts: all

  vars:
    IP: "0.0.0.0"
    PORT: "8000"

  tasks:
    # Runserver service
    - name: Deploy runserver
      copy:
        src: runserver.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Set ip:port configuration in service file
      replace:
        path: /etc/systemd/system/runserver.service
        regexp: "ip:port"
        replace: "{{IP}}:{{PORT}}"
      become: yes

    - name: Systemd daemon reload
      systemd:
        daemon_reload: yes
      become: yes

    - name: Disable runserver service
      service:
        name: runserver
        enabled: no
      become: yes

    - name: Enable runserver service
      service:
        name: runserver
        enabled: yes
      become: yes

    - name: Start runserver
      systemd:
        name: runserver
        state: started
      become: yes

    # Yarn devw service
    - name: Deploy yarn devw
      copy:
        src: yarn_devw.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Deploy yarn
      copy:
        src: yarn.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Systemd daemon reload
      systemd:
        daemon_reload: yes
      become: yes

    - name: Disable yarn_devw service
      service:
        name: yarn_devw
        enabled: no
      become: yes

    - name: Enable yarn_devw service
      service:
        name: yarn_devw
        enabled: yes
      become: yes

    - name: Start yarn
      systemd:
        name: yarn
        state: started
        enabled: no
      become: yes

    - name: Start yarn_devw
      systemd:
        name: yarn_devw
        state: started
      become: yes

    # RQworker1
    - name: Deploy rqworker1
      copy:
        src: rqworker1.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Systemd daemon reload
      systemd:
        daemon_reload: yes
      become: yes

    - name: Disable rqworker1 service
      service:
        name: rqworker1
        enabled: no
      become: yes

    - name: Enable rqworker1 service
      service:
        name: rqworker1
        enabled: yes
      become: yes

    - name: Start rqworker1
      systemd:
        name: rqworker1
        state: started
      become: yes

    # RQworker2
    - name: Deploy rqworker2
      copy:
        src: rqworker2.service
        dest: /etc/systemd/system/
        force: yes
      become: yes

    - name: Systemd daemon reload
      systemd:
        daemon_reload: yes
      become: yes

    - name: Disable rqworker2 service
      service:
        name: rqworker2
        enabled: no
      become: yes

    - name: Enable rqworker2 service
      service:
        name: rqworker2
        enabled: yes
      become: yes

    - name: Start rqworker2
      systemd:
        name: rqworker2
        state: started
      become: yes
