yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@bokeh/bokehjs@*":
    dependencies:
      "@bokeh/numbro": "*"
      "@bokeh/slickgrid": "*"
      "choices.js": "*"
      "flatbush": "*"
      "flatpickr": "*"
      "hammerjs": "*"
      "mathjax-full": "*"
      "nouislider": "*"
      "proj4": "*"
      "regl": "*"
      "sprintf-js": "*"
      "timezone": "*"
      "underscore.template": "*"
