# Generated by Django 2.1.13 on 2020-01-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191020_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsosData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dane studentów wyeksportowane z usosa',
                'verbose_name_plural': 'Dane studentów wyeksportowane z usosa',
            },
        ),
    ]
