# Generated by Django 2.1.15 on 2020-03-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200219_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='block',
        ),
    ]
