# Generated by Django 2.1.15 on 2020-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200324_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ects_in_semester',
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Student może być aktywny lub skreślony.', verbose_name='aktywny'),
        ),
        migrations.RunSQL(sql='''
            UPDATE users_student
            SET is_active = NOT (status::bool)
        '''),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
