# Generated by Django 3.1.14 on 2023-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201029_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_native',
            field=models.BooleanField(default=False, help_text='Określa czy program studiów jest z instytutu informatyki czy spoza np. matematyka', verbose_name='Program rodzimy'),
        ),
    ]
