# Generated by Django 3.1.14 on 2023-06-01 13:04

from django.db import migrations


def set_is_native(apps, schema_editor):
    Program = apps.get_model("users", "Program")
    for program in Program.objects.all():
        if any(x in program.name for x in ["Informatyka", "ISIM", "Data Science"]):
            program.is_native = True
            program.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0025_program_is_native'),
    ]

    operations = [
        migrations.RunPython(set_is_native),
    ]
