name: lint

on: 
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - uses: ./.github/actions/common
       
     - name: Lint Node assets
        run: |
          cd zapisy
          yarn lint
      - name: Lint Python
        run: |
          python -m flake8 --statistics .
