name: lint

on: 
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    env: 
      PYTHON_VERSION: 3.8
      NODE_VERSION: 12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v4
        with:
          path: zapisy/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('zapisy/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r zapisy/requirements.test.txt
      - name: Install Node Dependencies
        run: |
          cd zapisy
          yarnpkg install --immutable
      - name: Lint Node assets
        run: |
          cd zapisy
          yarn lint
      - name: Lint Python
        run: |
          python -m flake8 --statistics .