name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      PYTHON_VERSION: 3.8
      NODE_VERSION: 12
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: fereolpass
          POSTGRES_DB: fereol_test
        ports:
          - 5432:5432
        # Set health checks to wait until Postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v2
        with:
          path: zapisy/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('zapisy/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Set locale
        run: |
          sudo locale-gen pl_PL.UTF-8
          sudo update-locale LANG=pl_PL.UTF-8
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r zapisy/requirements.test.txt
      - name: Install Node Dependencies
        run: |
          cd zapisy
          yarnpkg install --immutable
      - name: Build Node assets
        run: |
          cd zapisy
          yarn dev:tc
      - name: Run Tests
        run: |
          mv env/.env_ci env/.env
          cd zapisy
          mkdir logs
          python manage.py test --failfast --parallel --nomigrations
